
spring:

  datasource:

    url: jdbc:mysql://13.125.232.54:3306/demo

    username: root

    password: 1234

    driver-class-name: com.mysql.cj.jdbc.Driver



  data:

    rest:

      base-path: /api

      default-page-size: 10

      max-page-size: 10

#      port : 8080



    jpa:

      hibernate:

        naming:

          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy



#server:

#  port: 8081





